DG v1.4 Preliminary Check
AY2021S1-CS2103-W14-3/tp pull request #159
Opened 2020-11-04 15:13 UTC by Jaylenlee

Note the following will need to be updated:

Model component -> ModelClassUDiagram (Add UniqueTagList and Tag to diagram)

Model component -> BetterModelClassDiagram (rename address book to expense book)

2020-11-07 17:47 UTC, maxxyh commented
> Note the following will need to be updated:
> 
> Model component -> ModelClassUDiagram (Add UniqueTagList and Tag to diagram)
> 
> Model component -> BetterModelClassDiagram (rename address book to expense book)

Sorry @Jaylenlee I don't really understand do we need to make these new diagrams?

2020-11-09 04:05 UTC, lebencwb requested changes
Thanks for updating the DG, @Jaylenlee! Most of it looks good to me - just one formatting issue to address and it should be good to go!

2020-11-09 04:05 UTC, lebencwb commented on docs/DeveloperGuide.md
> +_{more aspects and alternatives to be added}
I think there may be a formatting error here as the phrase is intended to be italicized.

2020-11-09 04:18 UTC, Jaylenlee commented on docs/DeveloperGuide.md
> +_{more aspects and alternatives to be added}
Thanks for the note! I have fixed it.

2020-11-09 04:20 UTC, lebencwb approved these changes
LGTM!

2020-11-09 04:22 UTC, merged